[package]
name = "propagate-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dev-dependencies]
trybuild = "1.0.101"

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.89", features = ["extra-traits"] }
proc-macro2 = "1.0.92"
hashbrown = "0.15.2"
